// week7-content.js — DWB Week 7: Income Streams & Side Hustles
// Days 43–49 | Named export | 10 overlays per video
// Showcases: liquid-drip, text-clip, outline-stroke, split-reveal, blur-in,
//            flip-up, letter-drop, panel-split, kinetic, word-bounce,
//            gradient-shift, outline-fill, color-burn
// ─────────────────────────────────────────────────────────────────────────────

export const week7Videos = [

  // ── DAY 43 ────────────────────────────────────────────────────────────────
  {
    id: "day43",
    filename: "day43_final.mp4",
    title: "Day 43 — 7 Income Streams",
    tiktokCaption: "The rich don't have 1 income stream. They have 7. Here's what they are. 💰 #wealthbuilding #incomestreams #personalfinance #financialfreedom #moneyhabits",
    youtubeTitle: "The 7 Income Streams of Every Rich Person (Day 43/90)",
    youtubeDescription: "Most people have 1 income stream. The wealthy have 7. In this video we break down all 7 — and which ones you can start TODAY with $0.\n\nDISCLOSURE: Some links may be affiliate links. If you click and purchase, I may earn a commission at no extra cost to you.\n\n#wealthbuilding #personalfinance #moneytips #financialfreedom #moneyhabits",
    pinnedComment: "Which income stream are you building right now? Drop it below 👇",
    bRollQueries: [
      "entrepreneur multiple income streams vertical",
      "passive income money flowing vertical",
      "wealthy lifestyle luxury apartment vertical",
      "stock portfolio growth chart vertical",
    ],
    musicMood: "motivational",
    colorGrade: "gold",
    overlays: [
      // 0 — HOOK (liquid-drip)
      {
        text: "THE RICH HAVE 7 INCOME STREAMS",
        animation: "liquid-drip",
        position: "top-center",
        font: "Anton",
        fontSize: 78,
        color: "#FFFFFF",
        glowColor: "#E8A920",
        startFrame: 0,
        endFrame: 120,
      },
      // 1 — PATTERN INTERRUPT (word-bounce)
      {
        text: "You only have ONE.",
        animation: "word-bounce",
        position: "middle",
        font: "Archivo",
        fontSize: 72,
        color: "#FF4560",
        startFrame: 120,
        endFrame: 210,
      },
      // 2 — AGITATE (blur-in)
      {
        text: "That's why you're always broke.",
        animation: "blur-in",
        position: "middle",
        font: "Montserrat",
        fontSize: 64,
        color: "#FFFFFF",
        startFrame: 210,
        endFrame: 300,
      },
      // 3 — LIST ITEM 1 (flip-up)
      {
        text: "1. EARNED INCOME\n(Your job. Active.)",
        animation: "flip-up",
        position: "middle",
        font: "Bebas",
        fontSize: 72,
        color: "#E8A920",
        startFrame: 300,
        endFrame: 390,
      },
      // 4 — LIST ITEM 2 (panel-split)
      {
        text: "2. BUSINESS INCOME\n(You own the system.)",
        animation: "panel-split",
        position: "middle",
        font: "Bebas",
        fontSize: 68,
        color: "#FFFFFF",
        accentColor: "#E8A920",
        startFrame: 390,
        endFrame: 480,
      },
      // 5 — LIST ITEM 3 (split-reveal)
      {
        text: "3. INTEREST\n4. DIVIDENDS\n5. RENT",
        animation: "split-reveal",
        position: "middle",
        font: "Anton",
        fontSize: 68,
        color: "#00D68F",
        startFrame: 480,
        endFrame: 570,
      },
      // 6 — FORMULA (kinetic)
      {
        text: "6. ROYALTIES 7. AFFILIATE",
        animation: "kinetic",
        position: "middle",
        font: "Anton",
        fontSize: 72,
        color: "#FFFFFF",
        accentColor: "#E8A920",
        startFrame: 570,
        endFrame: 660,
      },
      // 7 — PROOF (gradient-shift)
      {
        text: "Warren Buffett earns while he sleeps.",
        animation: "gradient-shift",
        position: "middle",
        font: "Montserrat",
        fontSize: 62,
        color: "#FFFFFF",
        hue1: 45,
        hue2: 120,
        startFrame: 660,
        endFrame: 750,
      },
      // 8 — APPLY (outline-fill)
      {
        text: "Pick ONE passive stream.\nStart this week.",
        animation: "outline-fill",
        position: "middle",
        font: "Archivo",
        fontSize: 68,
        color: "#E8A920",
        strokeColor: "#E8A920",
        fillColor: "#E8A920",
        startFrame: 750,
        endFrame: 840,
      },
      // 9 — CTA (color-burn)
      {
        text: "FOLLOW FOR\nDAILY WEALTH TIPS ⬡",
        animation: "color-burn",
        position: "bottom-center",
        font: "Anton",
        fontSize: 72,
        color: "#FFFFFF",
        burnColor: "#E8A920",
        startFrame: 840,
        endFrame: 900,
      },
    ],
  },

  // ── DAY 44 ────────────────────────────────────────────────────────────────
  {
    id: "day44",
    filename: "day44_final.mp4",
    title: "Day 44 — Side Hustle $0 Start",
    tiktokCaption: "5 side hustles that cost literally $0 to start. No excuses left. 🚀 #sidehustle #makemoney #wealthbuilding #personalfinance #financialfreedom",
    youtubeTitle: "5 Side Hustles That Cost $0 To Start (Day 44/90)",
    youtubeDescription: "No money? No problem. These 5 side hustles require zero startup cost. All you need is your phone or laptop.\n\nDISCLOSURE: Some links may be affiliate links.\n\n#wealthbuilding #personalfinance #moneytips #financialfreedom #moneyhabits",
    pinnedComment: "Which $0 side hustle are you starting? Comment below 👇",
    bRollQueries: [
      "person working laptop cafe side hustle vertical",
      "freelancer success phone vertical",
      "entrepreneur startup hustle vertical",
      "digital income online money vertical",
    ],
    musicMood: "punchy",
    colorGrade: "teal",
    overlays: [
      // 0 — HOOK (outline-stroke)
      {
        text: "5 SIDE HUSTLES.\n$0 TO START.",
        animation: "outline-stroke",
        position: "top-center",
        font: "Anton",
        fontSize: 82,
        color: "transparent",
        strokeColor: "#FFFFFF",
        strokeWidth: 5,
        startFrame: 0,
        endFrame: 120,
      },
      // 1 — PATTERN (word-bounce)
      {
        text: "\"I don't have money to invest\"",
        animation: "word-bounce",
        position: "middle",
        font: "Montserrat",
        fontSize: 60,
        color: "#FF4560",
        italic: true,
        startFrame: 120,
        endFrame: 220,
      },
      // 2 — AGITATE (blur-in)
      {
        text: "This excuse just expired.",
        animation: "blur-in",
        position: "middle",
        font: "Archivo",
        fontSize: 70,
        color: "#FFFFFF",
        startFrame: 220,
        endFrame: 310,
      },
      // 3 — HUSTLE 1 (letter-drop)
      {
        text: "1. FREELANCE WRITING\n→ Fiverr, Upwork",
        animation: "letter-drop",
        position: "middle",
        font: "Bebas",
        fontSize: 68,
        color: "#00D68F",
        startFrame: 310,
        endFrame: 400,
      },
      // 4 — HUSTLE 2 (flip-up)
      {
        text: "2. SOCIAL MEDIA MGMT\n→ $300–$1500/month",
        animation: "flip-up",
        position: "middle",
        font: "Bebas",
        fontSize: 64,
        color: "#E8A920",
        startFrame: 400,
        endFrame: 490,
      },
      // 5 — HUSTLE 3 (panel-split)
      {
        text: "3. AI PROMPT SELLING\n→ PromptBase",
        animation: "panel-split",
        position: "middle",
        font: "Bebas",
        fontSize: 66,
        color: "#FFFFFF",
        accentColor: "#00D68F",
        startFrame: 490,
        endFrame: 580,
      },
      // 6 — HUSTLE 4+5 (kinetic)
      {
        text: "4. AFFILIATE\n5. RESELLING",
        animation: "kinetic",
        position: "middle",
        font: "Anton",
        fontSize: 72,
        color: "#FFFFFF",
        accentColor: "#E8A920",
        startFrame: 580,
        endFrame: 670,
      },
      // 7 — PROOF (text-clip)
      {
        text: "People quit $50K jobs for these.",
        animation: "text-clip",
        position: "middle",
        font: "Anton",
        fontSize: 70,
        color: "#FFFFFF",
        clipColor1: "#E8A920",
        clipColor2: "#00D68F",
        clipColor3: "#3FB0F5",
        startFrame: 670,
        endFrame: 760,
      },
      // 8 — APPLY (split-reveal)
      {
        text: "Pick one. Start today.\nNot Monday.",
        animation: "split-reveal",
        position: "middle",
        font: "Archivo",
        fontSize: 68,
        color: "#E8A920",
        startFrame: 760,
        endFrame: 850,
      },
      // 9 — CTA (liquid-drip)
      {
        text: "SAVE THIS\nTHANK ME LATER ⬡",
        animation: "liquid-drip",
        position: "bottom-center",
        font: "Anton",
        fontSize: 74,
        color: "#FFFFFF",
        glowColor: "#00D68F",
        startFrame: 850,
        endFrame: 900,
      },
    ],
  },

  // ── DAY 45 ────────────────────────────────────────────────────────────────
  {
    id: "day45",
    filename: "day45_final.mp4",
    title: "Day 45 — Affiliate Marketing Explained",
    tiktokCaption: "You recommend it. Someone buys it. You get paid. That's affiliate marketing. 💸 #affiliatemarketing #passiveincome #wealthbuilding #makemoneyonline",
    youtubeTitle: "Affiliate Marketing Explained in 30 Seconds (Day 45/90 Milestone)",
    youtubeDescription: "Affiliate marketing is the simplest form of passive income. You share a link. Someone clicks. Someone buys. You earn a commission. No product. No customer support. No inventory.\n\nDISCLOSURE: Some links may be affiliate links.\n\n#wealthbuilding #personalfinance #moneytips #financialfreedom #moneyhabits",
    pinnedComment: "Have you tried affiliate marketing? What worked for you?",
    bRollQueries: [
      "affiliate marketing passive income laptop vertical",
      "money appearing phone notification vertical",
      "entrepreneur success online income vertical",
      "city aerial financial district night vertical",
    ],
    musicMood: "confident",
    colorGrade: "purple",
    overlays: [
      // 0 — HOOK (text-clip — milestone day 45)
      {
        text: "AFFILIATE MARKETING\nIN 30 SECONDS",
        animation: "text-clip",
        position: "top-center",
        font: "Anton",
        fontSize: 76,
        color: "#FFFFFF",
        clipColor1: "#A374FF",
        clipColor2: "#E8A920",
        clipColor3: "#00D68F",
        startFrame: 0,
        endFrame: 120,
      },
      // 1 — STEP 1 (flip-up)
      {
        text: "STEP 1:\nJoin a free program",
        animation: "flip-up",
        position: "middle",
        font: "Bebas",
        fontSize: 74,
        color: "#FFFFFF",
        startFrame: 120,
        endFrame: 210,
      },
      // 2 — STEP 2 (panel-split)
      {
        text: "STEP 2:\nGet your unique link",
        animation: "panel-split",
        position: "middle",
        font: "Bebas",
        fontSize: 74,
        color: "#FFFFFF",
        accentColor: "#A374FF",
        startFrame: 210,
        endFrame: 300,
      },
      // 3 — STEP 3 (letter-drop)
      {
        text: "STEP 3:\nShare it anywhere",
        animation: "letter-drop",
        position: "middle",
        font: "Bebas",
        fontSize: 74,
        color: "#A374FF",
        startFrame: 300,
        endFrame: 390,
      },
      // 4 — STEP 4 (word-bounce)
      {
        text: "STEP 4:\nSomeone buys → You earn",
        animation: "word-bounce",
        position: "middle",
        font: "Anton",
        fontSize: 70,
        color: "#00D68F",
        startFrame: 390,
        endFrame: 480,
      },
      // 5 — FORMULA (kinetic)
      {
        text: "NO product\nNO support\nNO inventory",
        animation: "kinetic",
        position: "middle",
        font: "Archivo",
        fontSize: 68,
        color: "#FFFFFF",
        accentColor: "#A374FF",
        startFrame: 480,
        endFrame: 570,
      },
      // 6 — PROOF (gradient-shift)
      {
        text: "Top affiliates earn $10K–$100K/mo",
        animation: "gradient-shift",
        position: "middle",
        font: "Anton",
        fontSize: 66,
        color: "#FFFFFF",
        hue1: 270,
        hue2: 45,
        startFrame: 570,
        endFrame: 660,
      },
      // 7 — BARRIER DESTROY (color-burn)
      {
        text: "You don't need an audience.\nYou need a link.",
        animation: "color-burn",
        position: "middle",
        font: "Montserrat",
        fontSize: 62,
        color: "#FFFFFF",
        burnColor: "#A374FF",
        startFrame: 660,
        endFrame: 750,
      },
      // 8 — APPLY (outline-fill)
      {
        text: "Start: Amazon Associates\nJoin FREE today",
        animation: "outline-fill",
        position: "middle",
        font: "Bebas",
        fontSize: 70,
        color: "#E8A920",
        strokeColor: "#E8A920",
        startFrame: 750,
        endFrame: 840,
      },
      // 9 — CTA (outline-stroke — milestone treatment)
      {
        text: "DAY 45 OF 90 ⬡\nHALFWAY. LET'S GO.",
        animation: "outline-stroke",
        position: "bottom-center",
        font: "Anton",
        fontSize: 78,
        strokeColor: "#A374FF",
        strokeWidth: 4,
        startFrame: 840,
        endFrame: 900,
      },
    ],
  },

  // ── DAY 46 ────────────────────────────────────────────────────────────────
  {
    id: "day46",
    filename: "day46_final.mp4",
    title: "Day 46 — Content = ATM Machine",
    tiktokCaption: "Every piece of content you post is a tiny ATM. Here's the math. 🏧 #contentcreator #passiveincome #digitalmarketing #wealthbuilding #makemoneyonline",
    youtubeTitle: "Every Piece of Content Is an ATM (Here's the Math) — Day 46/90",
    youtubeDescription: "Content is a compounding asset. One video made in 30 minutes can earn for 10 years. We break down the math of content as passive income.\n\nDISCLOSURE: Some links may be affiliate links.\n\n#wealthbuilding #personalfinance #moneytips",
    pinnedComment: "How many pieces of content have you published this month? Be honest.",
    bRollQueries: [
      "content creator phone filming vertical",
      "viral social media notification vertical",
      "ATM machine money withdrawal vertical",
      "compound interest graph growth vertical",
    ],
    musicMood: "rebellious",
    colorGrade: "red",
    overlays: [
      { text: "EVERY POST YOU MAKE\nIS AN ATM", animation: "liquid-drip", position: "top-center", font: "Anton", fontSize: 78, color: "#FFFFFF", glowColor: "#FF4560", startFrame: 0, endFrame: 120 },
      { text: "It pays you while you sleep.", animation: "blur-in", position: "middle", font: "Montserrat", fontSize: 64, color: "#FFFFFF", italic: true, startFrame: 120, endFrame: 220 },
      { text: "1 video → 1,000 views/day", animation: "flip-up", position: "middle", font: "Bebas", fontSize: 76, color: "#E8A920", startFrame: 220, endFrame: 310 },
      { text: "1,000 views/day\n→ $3–10/day from ads", animation: "panel-split", position: "middle", font: "Bebas", fontSize: 68, color: "#FFFFFF", accentColor: "#FF4560", startFrame: 310, endFrame: 400 },
      { text: "$5/day × 365 days\n= $1,825/year PER VIDEO", animation: "kinetic", position: "middle", font: "Anton", fontSize: 66, color: "#00D68F", accentColor: "#E8A920", startFrame: 400, endFrame: 490 },
      { text: "ADD affiliate links\nADD sponsorships", animation: "split-reveal", position: "middle", font: "Archivo", fontSize: 68, color: "#FFFFFF", startFrame: 490, endFrame: 580 },
      { text: "MrBeast has 500+ videos.\nEach one still earns.", animation: "gradient-shift", position: "middle", font: "Montserrat", fontSize: 60, color: "#FFFFFF", hue1: 0, hue2: 45, startFrame: 580, endFrame: 680 },
      { text: "You're not behind.\nYou just haven't started.", animation: "color-burn", position: "middle", font: "Montserrat", fontSize: 62, color: "#FFFFFF", burnColor: "#FF4560", startFrame: 680, endFrame: 770 },
      { text: "Post something today.\nEven imperfect.", animation: "outline-fill", position: "middle", font: "Archivo", fontSize: 66, color: "#E8A920", strokeColor: "#E8A920", startFrame: 770, endFrame: 860 },
      { text: "FOLLOW ⬡\n@DailyWealthBuilding", animation: "word-bounce", position: "bottom-center", font: "Anton", fontSize: 70, color: "#FFFFFF", startFrame: 860, endFrame: 900 },
    ],
  },

  // ── DAY 47 ────────────────────────────────────────────────────────────────
  {
    id: "day47",
    filename: "day47_final.mp4",
    title: "Day 47 — Sell Your Knowledge",
    tiktokCaption: "You know something other people need to learn. That's a product. 📚 #infoproducts #sellknowledge #passiveincome #wealthbuilding #onlinebusiness",
    youtubeTitle: "You Know Something Worth $27 (Here's How to Sell It) — Day 47/90",
    youtubeDescription: "Everyone has expertise worth packaging. Your knowledge is a product. We show you how to turn what you already know into income.\n\nDISCLOSURE: Some links may be affiliate links.\n\n#wealthbuilding #personalfinance #moneytips",
    pinnedComment: "What skill do you have that other people would pay to learn?",
    bRollQueries: [
      "person teaching laptop course online vertical",
      "knowledge books success entrepreneur vertical",
      "digital product download laptop vertical",
      "freelancer expert skill vertical",
    ],
    musicMood: "focused",
    colorGrade: "teal",
    overlays: [
      { text: "YOUR KNOWLEDGE\nIS WORTH $27", animation: "text-clip", position: "top-center", font: "Anton", fontSize: 80, color: "#FFFFFF", clipColor1: "#00D68F", clipColor2: "#3FB0F5", clipColor3: "#E8A920", startFrame: 0, endFrame: 120 },
      { text: "You've been giving it away FREE.", animation: "word-bounce", position: "middle", font: "Montserrat", fontSize: 64, color: "#FF4560", italic: true, startFrame: 120, endFrame: 220 },
      { text: "What do people ask\nyou for advice on?", animation: "blur-in", position: "middle", font: "Archivo", fontSize: 68, color: "#FFFFFF", startFrame: 220, endFrame: 310 },
      { text: "That. Is. A. Product.", animation: "letter-drop", position: "middle", font: "Anton", fontSize: 82, color: "#E8A920", startFrame: 310, endFrame: 400 },
      { text: "PDF guide → $9\nMini course → $27\nWorkshop → $97", animation: "panel-split", position: "middle", font: "Bebas", fontSize: 66, color: "#FFFFFF", accentColor: "#00D68F", startFrame: 400, endFrame: 490 },
      { text: "Platform: Gumroad\nSetup time: 2 hours\nCost: $0", animation: "split-reveal", position: "middle", font: "Bebas", fontSize: 66, color: "#00D68F", startFrame: 490, endFrame: 580 },
      { text: "10 sales/month at $27\n= $270 PASSIVE", animation: "kinetic", position: "middle", font: "Anton", fontSize: 72, color: "#FFFFFF", accentColor: "#E8A920", startFrame: 580, endFrame: 670 },
      { text: "Teachers earn 8hrs then stop.\nDigital products earn forever.", animation: "gradient-shift", position: "middle", font: "Montserrat", fontSize: 56, color: "#FFFFFF", hue1: 160, hue2: 45, startFrame: 670, endFrame: 760 },
      { text: "Write the outline.\nJust 5 bullet points.", animation: "outline-fill", position: "middle", font: "Archivo", fontSize: 66, color: "#00D68F", strokeColor: "#00D68F", startFrame: 760, endFrame: 850 },
      { text: "DAY 47/90 ⬡\nFOLLOW THE JOURNEY", animation: "color-burn", position: "bottom-center", font: "Anton", fontSize: 72, color: "#FFFFFF", burnColor: "#00D68F", startFrame: 850, endFrame: 900 },
    ],
  },

  // ── DAY 48 ────────────────────────────────────────────────────────────────
  {
    id: "day48",
    filename: "day48_final.mp4",
    title: "Day 48 — The 1% Rule",
    tiktokCaption: "Improve 1% every day for a year. The result will shock you. 📈 #1percentbetter #selfimprovement #wealthmindset #compoundeffect #dailyhabits",
    youtubeTitle: "Improve 1% Daily — The Math That Changes Everything (Day 48/90)",
    youtubeDescription: "1% improvement daily = 37x better in a year. The math of compound growth applied to your habits, skills, and income.\n\nDISCLOSURE: Some links may be affiliate links.\n\n#wealthbuilding #personalfinance #moneytips",
    pinnedComment: "What are you improving 1% at right now?",
    bRollQueries: [
      "compound growth chart upward trend vertical",
      "athlete training improvement discipline vertical",
      "person progress journal habit tracker vertical",
      "city sunrise motivation hustle vertical",
    ],
    musicMood: "dramatic",
    colorGrade: "blue",
    overlays: [
      { text: "1% BETTER\nEVERY DAY", animation: "outline-stroke", position: "top-center", font: "Anton", fontSize: 84, strokeColor: "#3FB0F5", strokeWidth: 5, startFrame: 0, endFrame: 120 },
      { text: "Sounds too small to matter.", animation: "blur-in", position: "middle", font: "Montserrat", fontSize: 64, color: "#FFFFFF", italic: true, startFrame: 120, endFrame: 210 },
      { text: "Here's the math:", animation: "word-bounce", position: "middle", font: "Anton", fontSize: 76, color: "#E8A920", startFrame: 210, endFrame: 280 },
      { text: "1% daily × 365 days\n= 37.78x BETTER", animation: "kinetic", position: "middle", font: "Anton", fontSize: 72, color: "#FFFFFF", accentColor: "#3FB0F5", startFrame: 280, endFrame: 380 },
      { text: "1% WORSE daily × 365\n= 0.03 of yourself", animation: "color-burn", position: "middle", font: "Bebas", fontSize: 74, color: "#FF4560", burnColor: "#FF0000", startFrame: 380, endFrame: 470 },
      { text: "Apply to WEALTH:\n+1% savings rate monthly", animation: "flip-up", position: "middle", font: "Bebas", fontSize: 68, color: "#00D68F", startFrame: 470, endFrame: 560 },
      { text: "Apply to SKILLS:\n+1% better at your craft daily", animation: "split-reveal", position: "middle", font: "Bebas", fontSize: 64, color: "#FFFFFF", startFrame: 560, endFrame: 650 },
      { text: "James Clear proved it.\nAthletes use it.\nNow you know.", animation: "gradient-shift", position: "middle", font: "Montserrat", fontSize: 60, color: "#FFFFFF", hue1: 200, hue2: 120, startFrame: 650, endFrame: 750 },
      { text: "What's your 1% today?", animation: "outline-fill", position: "middle", font: "Archivo", fontSize: 72, color: "#3FB0F5", strokeColor: "#3FB0F5", startFrame: 750, endFrame: 840 },
      { text: "FOLLOW ⬡\nDAILY WEALTH TIPS", animation: "text-clip", position: "bottom-center", font: "Anton", fontSize: 72, color: "#FFFFFF", clipColor1: "#3FB0F5", clipColor2: "#E8A920", clipColor3: "#00D68F", startFrame: 840, endFrame: 900 },
    ],
  },

  // ── DAY 49 ────────────────────────────────────────────────────────────────
  {
    id: "day49",
    filename: "day49_final.mp4",
    title: "Day 49 — Week 7 Wrap: Your Action Plan",
    tiktokCaption: "Week 7 done. 49 days in. Here's your action plan from this week's lessons. 🎯 #wealthbuilding #weeklyreview #sidehustle #incomestreams #financialfreedom",
    youtubeTitle: "Week 7 Wrap: Your 5-Step Income Action Plan (Day 49/90)",
    youtubeDescription: "Week 7 complete. 49 days in. Here's everything we covered this week distilled into 5 actionable steps you can do RIGHT NOW.\n\nDISCLOSURE: Some links may be affiliate links.\n\n#wealthbuilding #personalfinance #moneytips",
    pinnedComment: "Share your biggest win from Week 7 below! 👇",
    bRollQueries: [
      "entrepreneur success celebration vertical",
      "action plan notebook strategy vertical",
      "income growth chart upward vertical",
      "motivated person working hustle vertical",
    ],
    musicMood: "uplifting",
    colorGrade: "gold",
    overlays: [
      { text: "WEEK 7 DONE.\n49 DAYS STRONG.", animation: "liquid-drip", position: "top-center", font: "Anton", fontSize: 78, color: "#FFFFFF", glowColor: "#E8A920", startFrame: 0, endFrame: 130 },
      { text: "Here's what you learned:", animation: "word-bounce", position: "middle", font: "Archivo", fontSize: 66, color: "#E8A920", startFrame: 130, endFrame: 210 },
      { text: "1. 7 income streams exist\n2. $0 side hustles work", animation: "flip-up", position: "middle", font: "Bebas", fontSize: 68, color: "#FFFFFF", startFrame: 210, endFrame: 310 },
      { text: "3. Affiliate = recommend + earn\n4. Content compounds forever", animation: "panel-split", position: "middle", font: "Bebas", fontSize: 64, color: "#00D68F", accentColor: "#E8A920", startFrame: 310, endFrame: 410 },
      { text: "5. Your knowledge = a product", animation: "letter-drop", position: "middle", font: "Anton", fontSize: 74, color: "#E8A920", startFrame: 410, endFrame: 500 },
      { text: "THIS WEEK'S CHALLENGE:", animation: "outline-stroke", position: "middle", font: "Anton", fontSize: 76, strokeColor: "#E8A920", strokeWidth: 4, startFrame: 500, endFrame: 580 },
      { text: "Pick 1 income stream.\nTake 1 action step.\nThis week.", animation: "kinetic", position: "middle", font: "Archivo", fontSize: 66, color: "#FFFFFF", accentColor: "#E8A920", startFrame: 580, endFrame: 680 },
      { text: "41 days left.\nThe second half starts NOW.", animation: "gradient-shift", position: "middle", font: "Montserrat", fontSize: 60, color: "#FFFFFF", hue1: 45, hue2: 160, startFrame: 680, endFrame: 770 },
      { text: "Share your progress\nin the comments ↓", animation: "color-burn", position: "middle", font: "Archivo", fontSize: 66, color: "#FFFFFF", burnColor: "#E8A920", startFrame: 770, endFrame: 855 },
      { text: "DAY 49/90 ⬡\n@DailyWealthBuilding", animation: "outline-fill", position: "bottom-center", font: "Anton", fontSize: 70, color: "#E8A920", strokeColor: "#E8A920", startFrame: 855, endFrame: 900 },
    ],
  },

];
